### ISSUE TITLE
Dialog Size

### ISSUE THREAD

**Issue by brunocalado** [theripper93/tile-scroll#1]
Hi! Thank you for this mod!

After you enable the scroll, close the dialog and open it again the dialog size is smaller then the fields in there. If you click the title you can fix it.

https://user-images.githubusercontent.com/4999783/189525057-d5627ee5-0df0-411c-affc-71e2146f56ad.mp4

Is it possible to make the dialog open in the right size? 

Tks

**Comment by theripper93** [comment]
fixed
