### ISSUE TITLE
Starting/Stopping Scrolling/Rotation

### ISSUE THREAD

**Issue by Viper0071955** [theripper93/tile-scroll#2]
I may be missing something, but I see no way to start/stop (rotation in this case) without opening the tile setup screen.  I am not familiar with code, but willing to try.  I also use Monk's Tile Triggers and also didn't see a way to do this as well.

Thanks for any help

**Comment by theripper93** [comment]
Please redirect help requests to my discord https://github.com/theripper93/Levels/blob/v9/ISSUES.md
