### ISSUE TITLE
Overhead Tiles glitch after scene refresh

### ISSUE THREAD

**Issue by Z3nner** [theripper93/tile-scroll#4]
Tiles placed in the foreground layer will freeze immediately on page reload.  Adjusting tile scroll settings produce no response after this happens and the tile can only be made to scroll again if it is deleted and replaced.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
