### ISSUE TITLE
Pause Function

### ISSUE THREAD

**Issue by PilotodeMouse** [theripper93/tile-scroll#5]
Hello. It's not a problem! :) It's a request!
Is there a way to put a pause button in the function?
I made some credits like a movie at the end of the adventure and used this feature!
It just keeps running constantly. I wanted to start when players entered the page! Could it be?

Gratitude! :)

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
