### ISSUE TITLE
Image quality loss with fast speeds

### ISSUE THREAD

**Issue by ClestonMoura** [theripper93/tile-scroll#6]
I'm using the module to create an interactive landing page for my players. So tile is set to the size of the scene. When I set the speed to be higher than 0.02, the image quality drops a lot.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
