### ISSUE TITLE
Feature Request: Pause tile scroll during combat.

### ISSUE THREAD

**Issue by aruguy** [theripper93/tile-scroll#8]
I set up a highway chase scene for my players in CyberpunkRED and found it a little disconcerting that the player/npc vehicle tokens just plowed through the never ending stream of oncoming traffic. Being able to pause Tile-Scroll during combat would allow GM's to bake obstacles into scrolling scenery and allow players to avoid them. An even better solution for this would be to link the scroll advancement to the initiative tracker so GM's can define a scrollspeed/round.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
