### ISSUE TITLE
Request: Separate speeds for when both scrolling and rotating.

### ISSUE THREAD

**Issue by ExileofBrokenSky** [theripper93/tile-scroll#9]
Would be great if it was possible to set differing speeds when both scrolling and rotation are enabled instead of both using the same value so the final visual result can be fine tuned.

**Comment by theripper93** [comment]
Hello! It seems you haven't read the [Before Posting an issue](https://theripper93.com/info/issues) as indicated at the top of the Repository Readme The Issue has been closed.

If you are reporting a bug, feel free to follow the steps here (https://theripper93.com/info/issues) and reopen the issue with all the relevant information.
